spring:
  application:
    name: agarang
  config:
    import: classpath:application-prod.yml
  profiles:
    active: local
    group:
      local: local, secret
      blue: blue, secret
      green: green, secret

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: true
    defer-datasource-initialization: true # Sql auto init after jpa ddl-auto operation
  servlet:
    multipart: # TODO: Exception Handler 추가하기
      max-file-size: 5MB
      max-request-size: 10MB
  sql: # Set src/main/resources/data.sql auto init
    init:
      mode: always
      data-locations: classpath:data.sql

aws:
  s3:
    upload:
      tempPath: ./temp/

springdoc:
  api-docs:
    path: /api-json
  swagger-ui:
    path: /api-docs # 302 /swagger-ui/index.html
    tags-sorter: alpha
    operations-sorter: alpha
  paths-to-exclude: /env
