spring:
  application:
    name: agarang
  config:
    import: classpath:application-prod.yml
  profiles:
    active: local
    group:
      local: local, secret
      blue: blue, secret
      green: green, secret

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: true
  servlet:
    multipart: # TODO: Exception Handler 추가하기
      max-file-size: 5MB
      max-request-size: 10MB