spring:
  config:
    activate:
      on-profile: local
  jpa:
    defer-datasource-initialization: true # Sql auto init after jpa ddl-auto operation
  sql: # Set src/main/resources/data.sql auto init
    init:
      mode: always
      data-locations: classpath:data.sql

deploy:
  env: local
  address: localhost
  name: local_server

server:
  port: 8080