spring:
  config:
    activate:
      on-profile: blue

server:
  port: 8080
deploy:
  env: blue
  name: blue_server

app:
  baseUrl: https://agarang.site

---
spring:
  config:
    activate:
      on-profile: green

server:
  port: 8081
deploy:
  env: green
  name: green_server

app:
  baseUrl: https://agarang.site