spring:
  config:
    activate:
      on-profile: blue

deploy:
  env: blue

app:
  baseUrl: https://www.agarang.site

---
spring:
  config:
    activate:
      on-profile: green

deploy:
  env: green

app:
  baseUrl: https://www.agarang.site