spring:
  application:
    name: agarang
  config:
    import: classpath:application-prod.yml
  profiles:
    active: local
    group:
      local: local, secret
      blue: blue, secret, prod
      green: green, secret, prod

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: true
  servlet:
    multipart: # TODO: Exception Handler 추가하기
      max-file-size: 5MB
      max-request-size: 10MB

  data:
    redis:
      repositories:
        enabled: false
    jpa:
      repositories:
        bootstrap-mode: deferred

aws:
  s3:
    upload:
      tempPath: ./temp/

springdoc:
  api-docs:
    path: /api-json
  swagger-ui:
    path: /api-docs # 302 /swagger-ui/index.html
    tags-sorter: alpha
    operations-sorter: alpha
  paths-to-exclude: /env

---
spring:
  config:
    activate:
      on-profile: blue

deploy:
  env: blue

---
spring:
  config:
    activate:
      on-profile: green

deploy:
  env: green